### ISSUE TITLE
Please provide Windows binaries

### ISSUE THREAD

**Issue by Carsten-Holbach** [aws-samples/aws-iot-securetunneling-localproxy#66] opened 2021-09-21 10:45 UTC
Hey!

Do you think it would be possible to provide Windows binaries? I think it would go a long way to making this feature more accessible, without having to go through the process to compile first for a situation where somebody would really like to do troubleshooting on a Thing (like I would like to now).

Thanks!

**Comment by ChelesaPan-AWS** [comment] 2021-09-23 16:53
Hi, 
We are considering this as a feature backlog and will let you know when it is available. 

Thank you!

**Comment by HarshGandhi-AWS** [comment] 2022-04-22 22:37
Hello @Carsten-Holbach  ,

Thank-you for your feedback, this feature has been requested by many of our customers, and that will be a strong influence on the prioritization of this feature. However, at this time we cannot provide a date for this feature. 

Closing this issue now, will post update once the issue is launched. 

Thank you,
Harsh Gandhi

**Closed by HarshGandhi-AWS** 2022-04-22 22:37 UTC
Labels: enhancement
