### ISSUE TITLE
Return Error while build for raspberry pi 4 compute module

### ISSUE THREAD

**Issue by albertshanhandoko** [aws-samples/aws-iot-securetunneling-localproxy#86] opened 2022-06-13 08:15 UTC
**Describe the bug**

When building local proxy it stopped and returns error at 58%

[ 58%] Linking CXX executable bin/localproxytest
/usr/bin/ld: /usr/local/lib/arm-linux-gnueabihf/libprotobuf-lite.a(arena.cc.o): in function `google::protobuf::internal::ThreadSafeArena::Init(bool)':
arena.cc:(.text+0xa60): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/localproxytest.dir/build.make:292: bin/localproxytest] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/localproxytest.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**To Reproduce**

1. Install All libraries and dependencies
2. git clone https://github.com/aws-samples/aws-iot-securetunneling-localproxy
3. cd aws-iot-securetunneling-localproxy
4. mkdir build
5. cd build
6. cmake ../
7. make
8. See Error

**Expected behavior**

Build complete successfully, binaries generated

**Actual behavior**

"make" command returns error

**Logs**
Attached
![image](https://user-images.githubusercontent.com/20452261/173309861-73a89a0b-9075-4fa6-b4ef-f4109de5c00d.png)

**Environment (please complete the following information):**
 - OS: Linux raspberrypi
 - Version  5.15.32-v7l+
 - Architecture: armv7l

**Comment by HarshGandhi-AWS** [comment] 2022-07-29 21:15
Hello @albertshanhandoko , 

I haven't seen the exact error yet for other OS but I will try to reproduce this issue on raspberry pi device. Will keep you posted with my progress. 

Regards, 
Harsh Gandhi

**Comment by HarshGandhi-AWS** [comment] 2022-09-06 18:08
Still facing some issue to install dependencies (boost) on Raspberry pi 4. Will continue working on it this week.

**Comment by HarshGandhi-AWS** [comment] 2022-09-19 17:41
Hello @albertshanhandoko , I have tried reproducing the issue you were facing on the Raspberry Pi 4 device but because of low computing power and other issues, I was not able to install all of the dependencies on the device. But when I tried to cross compile the binary for raspberry pi, it compiled without any build issues and also all local tests passed. 
I would suggest you to cross compile the localproxy binary on a different device and then use that binary on your Raspberry Pi device. 

Here are the steps which you can follow to cross compile localproxy binary: https://github.com/aws-samples/aws-iot-securetunneling-localproxy#cross-compilation

Please let us know if it works for you or not. 

Regards,
Harsh Gandhi

**Comment by HarshGandhi-AWS** [comment] 2022-09-26 21:39
Hello @albertshanhandoko , we are closing this issue now. Please feel free to reopen it or create a new issue if you find any difficulty in using localproxy. 

Thank you.

**Closed by HarshGandhi-AWS** 2022-09-26 21:39 UTC
Labels: bug
